name: DAM-TAG-DYM
channels:
  - pytorch
  - defaults
dependencies:
  - blas
  - boto
  - boto3
  - botocore
  - ca-certificates
  - cachetools
  - certifi
  - cffi
  - chardet
  - cryptography
  - cudatoolkit
  - decorator
  - docutils
  - freetype
  - gensim=3.8.0
  - google-cloud-core
  - google-cloud-storage
  - google-resumable-media
  - idna
  - intel-openmp
  - jmespath
  - joblib
  - jpeg=9b
  - libpng
  - libprotobuf
  - libtiff
  - lz4-c
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - networkx
  - ninja
  - numpy
  - numpy-base
  - olefile
  - openssl
  - pillow
  - pip
  - psutil
  - pyasn1
  - pycparser
  - pyopenssl
  - pysocks
  - python=3.7.9
  - python-dateutil=2.8.1
  - pytz
  - requests
  - rsa
  - s3transfer
  - scikit-learn
  - scipy
  - setuptools
  - six
  - smart_open
  - sqlite
  - threadpoolctl
  - tk
  - torchvision
  - wheel
  - xz
  - zlib
  - zstd

  - pip:
    - python-igraph
    - msgpack-python
    - cycler==0.10.0
    - google-api-core==1.20.0
    - google-auth==1.18.0
    - googleapis-common-protos==1.52.0
    - kiwisolver==1.2.0
    - mpmath==1.1.0
    - powerlaw==1.4.6
    - protobuf==3.12.2
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - urllib3==1.25.9
    - PyYAML==5.3.1
    - easydict==1.9
    - numpy==1.18.5
    - matplotlib==3.2.2
    - tqdm==4.48.2
    - pandas==1.0.5
    - scipy==1.4.1
    - setuptools==45.2.0
    - six==1.14.0
    - powerlaw==1.4.6
    - sklearn==0.0
    - scikit-learn==0.23.1
    - tensorboard==2.6.0
    - networkx==2.6.3
